variables:
  DOCKER_REPOSITORY: "mozmeao/snippets"

stages:
  - build
  - test
  - deploy

build-image-django:
  stage: build
  tags:
    - mozmeao
  script:
    - CI_COMMIT_SHORT_SHA=latest make pull app=web
    - make build app=web
    - make push app=web
    # With latest tag for caching
    - CI_COMMIT_SHORT_SHA=latest make build app=web
    - CI_COMMIT_SHORT_SHA=latest make push app=web

build-image-redirector:
  stage: build
  tags:
    - mozmeao
  script:
    - CI_COMMIT_SHORT_SHA=latest make pull app=web
    - make build app=redirector
    - make push app=redirector
    # With latest tag for caching
    - CI_COMMIT_SHORT_SHA=latest make build app=redirector
    - CI_COMMIT_SHORT_SHA=latest make push app=redirector

check-migrations:
  stage: test
  tags:
    - mozmeao
  script:
    - make check-migrations

run-flake8:
  stage: test
  tags:
    - mozmeao
  rules:
    - allow_failure: true
  script:
    - make lint

run-unit-tests-django:
  stage: test
  tags:
    - mozmeao
  script:
    - make test-web

run-unit-tests-redirector:
  tags:
    - mozmeao
  script:
    - make test-redirector

.deploy:
  stage: deploy
  tags:
    - mozmeao
    - aws
  script:
    - bin/update-config.sh

stage:
  extends: .deploy
  only:
    - stage
  variables:
    NAMESPACE: snippets-stage
    CLUSTERS: oregon-a
    DOCKER_IMAGE_TAG: "${DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}"

admin:
  extends: .deploy
  only:
    - admin
  variables:
    NAMESPACE: snippets-admin
    CLUSTERS: oregon-a
    DOCKER_IMAGE_TAG: "${DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}"

prod:
  extends: .deploy
  only:
    - prod
  variables:
    NAMESPACE: snippets-prod
    CLUSTERS: frankfurt-eks oregon-eks
    DOCKER_IMAGE_TAG: "${DOCKER_REPOSITORY}:redirector-${CI_COMMIT_SHORT_SHA}"
