variables:
  DOCKER_REPOSITORY: "mozmeao/snippets"
  DOCKER_IMAGE_TAG: "${DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}"
  # Cannot use $DOCKER_IMAGE_TAG because it contains other variables itself.
  DOCKER_RUN_CMD: "docker run --env-file .docker-env ${DOCKER_REPOSITORY}:${CI_COMMIT_SHORT_SHA}"

stages:
  - build
  - test
  - deploy

build-image-django:
  stage: build
  tags:
    - mozmeao
  script:
    - docker build -t ${DOCKER_IMAGE_TAG} --build-arg GIT_SHA=${CI_COMMIT_SHA} --pull .
    - docker push ${DOCKER_IMAGE_TAG}

build-image-redirector:
  stage: build
  tags:
    - mozmeao
  script:
    - docker build -t ${DOCKER_IMAGE_TAG}-redirector --build-arg GIT_SHA=${CI_COMMIT_SHA} --pull redirector/
    - docker push ${DOCKER_IMAGE_TAG}-redirector

.test-stage:
  stage: test
  variables:
    DOCKER_DEBUG: "False"
    DOCKER_ALLOWED_HOSTS: "*"
    DOCKER_SECRET_KEY: "foo"
    DOCKER_DATABASE_URL: "sqlite:///"
    DOCKER_SITE_URL: "http://localhost:8000"
    DOCKER_CACHE_URL: "dummy://"
    DOCKER_ENABLE_ADMIN: "True"
    DOCKER_SECURE_SSL_REDIRECT: "False"
  before_script:
    - env | grep "^DOCKER" | sed 's/DOCKER_//' > .docker-env

check-migrations:
  extends: .test-stage
  tags:
    - mozmeao
  script:
    - ${DOCKER_RUN_CMD} bash -c './manage.py makemigrations  | grep "No changes detected"'

run-flake8:
  extends: .test-stage
  tags:
    - mozmeao
  rules:
    - allow_failure: true
  script:
    - ${DOCKER_RUN_CMD} flake8 snippets

run-unit-tests-django:
  extends: .test-stage
  tags:
    - mozmeao
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  script:
    - ${DOCKER_RUN_CMD} bash -c 'coverage run ./manage.py test --parallel; coverage report'

run-unit-tests-redirector:
  extends: .test-stage
  tags:
    - mozmeao
  script:
    - docker run ${DOCKER_IMAGE_TAG}-redirector bash -c 'pytest test.py'

.deploy:
  stage: deploy
  tags:
    - mozmeao
    - aws
  script:
    - bin/update-config.sh

dev:
  extends: .deploy
  only:
    - master
  variables:
    NAMESPACE: snippets-dev
    CLUSTERS: oregon-a

stage:
  extends: .deploy
  only:
    - stage
  variables:
    NAMESPACE: snippets-stage
    CLUSTERS: oregon-a

admin:
  extends: .deploy
  only:
    - admin
  variables:
    NAMESPACE: snippets-admin
    CLUSTERS: oregon-a

prod:
  extends: .deploy
  only:
    - prod
  variables:
    NAMESPACE: snippets-prod
    CLUSTERS: frankfurt oregon-a
